#!/usr/bin/env python

'''
Copyright (c) 2021, The Monero Project

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors
may be used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
'''

import lmdb
from ctypes import *
import cmd

ADDRESS_MAX = 128

class db:
    def __init__(self):
        self.env = lmdb.open("/tmp/testbuild/data-dir", max_dbs=1)
        self.db = self.env.open_db("balance".encode())

    def __del__(self):

        self.env.close()

    def get_wallet(self, address):
        txn = self.env.begin(db=self.db, write=False)
        cur = txn.cursor()
        baddr = bytes(address, 'utf-8')
        dif = ADDRESS_MAX - len(baddr)
        baddr += b"\0" * dif
        amount = 0
        if cur.get(baddr):
            k, v = cur.item()
            amount = c_longlong.from_buffer_copy(v).value
        else:
            amount = -1
        cur.close()
        txn.abort()
        return address, amount

    def list_wallets(self):
        txn = self.env.begin(db=self.db, write=False)
        cur = txn.cursor()
        k = cur.first()
        wallets = []
        while k:
            addr, v = cur.item()
            addr = str(addr, 'utf-8').strip()
            wallets.append(addr)
            k = cur.next()
        return wallets

class walletEditCli(cmd.Cmd):
    intro = 'Backup your DB before any edit\nTest on a staging server first\nYou are responsible for any dataloss'
    prompt = "(wallet-edit) "

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.database = db()

    def do_get(self, arg):
        addr, amount =  self.database.get_wallet(arg)
        print("{}: {}".format(addr, amount))

    def do_list(self, arg):
        wallets = self.database.list_wallets()
        for w in wallets:
            print(w)

    def do_exit(self, arg):
        return True
        


if __name__ == "__main__":
    walletEditCli().cmdloop()